import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import HomePage from "../components/Home/Home";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Locum Zone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </div>
  );
}
